language: node_js
node_js:
  - "7"

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate
  - echo "zeroleaf.com" > public/CNAME

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  email: zeroleaf021@gmail.com
  name: zeroleaf
  on:
    branch: master

branches:
  only:
    - master